language: python
python: 2.7
env:
  matrix:
  - OST_ENGINE=jNeuroML
  - OST_ENGINE=NEURON
install:
- pip install git+https://github.com/borismarin/osb-model-validation.git@backend_class
script:
- omv all
