sudo: false
language: python
python: 2.7
env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=NEURON
    - OMV_ENGINE=genesis
before_install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation.git@conda
install:
    - eval $(omv travis-conda-setup)
script:
    - omv all
